#!/bin/bash
uname=$(uname -a)
card=$(nvidia-smi -L|tr '\n' '-')
topic='godParticle'
prompt="write me a blog post about the god particle"
date=$(date -I)
outputDir=output
resultsOutputDir=results
mkdir -p ${outputDir}
mkdir -p ${resultsOutputDir}
resultsOutput=${resultsOutputDir}/results-${date}.csv
if [[ -f ${resultsOutputDir} ]]; then
  resultsOutput=${resultsOutputDir}/results-${date}-$(date +%s.%N).csv
fi

echo "model,time,topic,prompt,card,uname,date" >> ${resultsOutput}
count_zero=0
for model in $(cat models)
  do 
    echo ${model} ${topic} ${prompt}
    ((count_zero++))
    # make a md header like so:
    # $topic #$countzero
    ### written by $model
    echo "# ${topic} #$count_zero" | tee -a ${outputDir}/"${topic}-${model}.md"
    echo "" | tee -a ${outputDir}/"${topic}-${model}.md"
    echo "### writen by ${model}" | tee -a ${outputDir}/"${topic}-${model}.md"
    echo "" | tee -a ${outputDir}/"${topic}-${model}.md"
    # time our run
    time1=$(date +%s.%N)
    ollama run ${model}  "${prompt}" | tee -a ${outputDir}/"${topic}-${model}.md"
    time2=$(date +%s.%N)

    diff=$(echo "scale=40;${time2} - ${time1}" | bc)
    # add another line to our output results
    echo "${model},${diff},${topic},${prompt},${card},${uname},${date}" |tee -a ${resultsOutput}
  done

time main 
